const express = require('express')
const router = express.Router()
const  UserController = require('../controllers/user')
const {upload} = require('../middlewares/uplodefile')
const {auth} = require('../middlewares/jwttoken')
router.post('/api/register',upload("user_image"),UserController.register)
router.post('/api/login',UserController.login)
router.get('/api/getallusers',auth,UserController.getallusers)
router.post('/api/deleteuser',auth,UserController.deleteuser)
router.get('/api/profile',auth,UserController.profile)
router.put('/api/updateuser:uid',upload("user_image"),auth,UserController.updateuser)
module.exports = router